apiVersion: v1
kind: Namespace
metadata:
  name: nginx-ingress
---
apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
  labels:
    certmanager.k8s.io/disable-validation: "true"
---
apiVersion: v1
kind: Namespace
metadata:
  name: chartmuseum
---
apiVersion: v1
kind: Namespace
metadata:
  name: harbor
