apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager

---
apiVersion: v1
kind: ServiceAccount
metadata: 
  name: tiller-cert-manager
  namespace: cert-manager

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tiller-cert-manager
  namespace: cert-manager
rules:
- apiGroups: ["", "batch", "extensions", "apps"]
  resources: ["*"]
  verbs: ["*"]