kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tiller-cert-manager
  namespace: cert-manager
rules:
- apiGroups: ["", "batch", "extensions", "apps"]
  resources: ["*"]
  verbs: ["*"]