apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tiller-cert-manager
  namespace: cert-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: tiller-cert-manager
subjects:
  - kind: ServiceAccount
    name: tiller-cert-manager
    namespace: cert-manager