apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: host-path-claim
spec:
  storageClassName: csi-hostpath-sc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi