---
apiVersion: v1
kind: Pod
metadata:
  name: storage-pod
  labels:
    app: web
spec:
  containers:
  - name: web
    image: pathfinder177/ki1:web-server
    volumeMounts:
    - name: app
      mountPath: /app
  initContainers:
  - name: busybox
    image: busybox:1.31.0
    command: ['sh', '-c', 'wget -O- https://raw.githubusercontent.com/express42/otus-platform-snippets/master/Module-02/Introduction-to-Kubernetes/wget.sh | sh']
    volumeMounts:
    - name: data
      mountPath: /data
    volumeMounts:
    - name: data
      mountPath: /data
      mountPropagation: "HostToContainer"
  volumes:
  - name: data
    persistentVolumeClaim:
      claimName: storage-pvc
