---
apiVersion: v1
kind: Pod
metadata:
  name: storage-pod
spec:
  restartPolicy: Always
  volumes:
    - name: host-path-csi-volume
      persistentVolumeClaim:
        claimName: storage-pvc
  containers: 
    - image: ubuntu
      command: ["/bin/sh", "-c"]
      args: [ "chmod 777 /data" ]
      name: ngalp
      volumeMounts:
        - name: host-path-csi-volume
          mountPath: "/data"