---
apiVersion: v1
kind: Pod
metadata:
  name: storage-pod
spec:
  restartPolicy: Always
  volumes:
    - name: host-path-csi-volume
      persistentVolumeClaim:
        claimName: host-path-claim
  containers: 
    - image: pathfinder177/kubehw1:ngalp
      name: ngalp
      volumeMounts:
        - name: host-path-csi-volume
          mountPath: "/data"