---
apiVersion: v1
kind: Pod
metadata:
  name: storage-pod
  labels:
    app: web
spec:
  containers:
  - name: web
    image: pathfinder177/ki1:web-server
    volumeMounts:
    - name: data
      mountPath: /data
    volumeMounts:
    - name: data
      mountPath: /data
      mountPropagation: "HostToContainer"
  volumes:
  - name: data
    persistentVolumeClaim:
      claimName: storage-pvc
