apiVersion: v1
kind: Pod
metadata:
  name: storage-pod
  labels:
    name: storage-pod
spec:
  restartPolicy: Always
  containers:
    - image: ubuntu
      command: ["/bin/sh", "-c"]
      args: [ "tail -f /dev/null" ]
      name: busybox
      volumeMounts:
        - name: vol
          mountPath: /data 
          mountPropagation: "HostToContainer"
  volumes:
    - name: vol
      persistentVolumeClaim:
        claimName: storage-pvc