apiVersion: v1
kind: Pod
metadata:
  name: storage-pod
  labels:
    app: storage-pod
spec:
  restartPolicy: Always
  volumes:
    - name: host-path-csi-volume
      persistentVolumeClaim:
        claimName: host-path-claim
  containers:
  - name: web 
    image: pathfinder177/kubehw1:ngalp
    volumeMounts:
      - mountPath: "/data"
        name: host-path-csi-volume
  initContainers:
  - name: generate-index
    image: busybox:1.31.0
    command: ['sh', '-c', 'wget -O- https://raw.githubusercontent.com/express42/otus-platform-snippets/master/Module-02/Introduction-to-Kubernetes/wget.sh | sh']