---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: csi-host-path-storage-class
provisioner: hostpath.csi.k8s.io 
parameters:
  type: Filesystem
reclaimPolicy: Delete
allowVolumeExpansion: true
volumeBindingMode: Immediate
