---
apiVersion: v1
kind: Pod
metadata:
  name: storage-pod
  labels:
    name: storage-pod
spec:
  containers:
    - name: web
      image: pathfinder177/ki1:web-server
      command: ["/bin/sh", "-c"]
      args: [ "tail -f /dev/null" ]
      name: busybox
      volumeMounts:
        - name: vol
          mountPath: /data 
          mountPropagation: "HostToContainer"
  volumes:
  - name: vol
    persistentVolumeClaim:
      claimName: storage-pvc
