kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: netperf-operator
rules:
- apiGroups:
  - app.example.com
  resources:
  - "*"
  verbs:
  - "*"
- apiGroups:
  - ""
  resources:
  - pods
  - pods/log
  verbs:
  - "*"
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: default-account-netperf-operator
subjects:
- kind: ServiceAccount
  name: default
roleRef:
  kind: Role
  name: netperf-operator
  apiGroup: rbac.authorization.k8s.io
