apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kube-iptables-tailer
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs:     ["list","get","watch"]
- apiGroups: [""]
  resources: ["events"]
  verbs:     ["patch","create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kube-iptables-tailer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kube-iptables-tailer
subjects:
- kind: ServiceAccount
  name: kube-iptables-tailer
  namespace: kube-system

