---
apiVersion: v1
kind: Service
metadata:
  name: core-dns-lb-tcp
  namespace: kube-system
  annotations: 
    metallb.universe.tf/allow-shared-ip: core
spec:
  selector:
    k8s-app: kube-dns
  type: LoadBalancer
  loadBalancerIP: 172.17.255.5
  ports:
    - protocol: TCP
      port: 53
      targetPort: 53

---
apiVersion: v1
kind: Service
metadata:
  name: core-dns-lb-udp
  namespace: kube-system
  annotations: 
    metallb.universe.tf/allow-shared-ip: core
spec:
  selector:
    k8s-app: kube-dns
  type: LoadBalancer
  loadBalancerIP: 172.17.255.5
  ports:
    - protocol: UDP
      port: 53
      targetPort: 53
