apiVersion: v1
kind: Pod
metadata:
  name: host-path-pod
spec:
  restartPolicy: Always
  volumes:
    - name: host-path-csi-volume
      persistentVolumeClaim:
        claimName: host-path-claim
  containers:
    - name: ngalp
      image: pathfinder177/kubehw1:ngalp
      imagePullPolicy: IfNotPresent
      volumeMounts:
      - mountPath: "/data"
        name: host-path-csi-volume
