apiVersion: v1
kind: PersistentVolume
metadata:
  name: host-path-volume
spec:
  storageClassName: csi-hostpath-sc
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/opt"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata: host-path-claim
spec:
  storageClassName: csi-hostpath-sc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi

---

apiVersion: v1
kind: Pod
metadata:
  name: host-path-pod
spec:
  volumes:
    - name: host-path-volume
      persistentVolumeClaim:
        claimName: host-path-claim
  containers:
    - name: ngalp
      image: pathfinder177/kubehw1:ngalp
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - mountPath: "/data"
        name: host-path-volume
