apiVersion: v1
kind: PersistentVolume
metadata:
  name: host-path-volume
spec:
  storageClassName: csi-hostpath-sc
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/opt"
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: host-path-claim
spec:
  storageClassName: csi-hostpath-sc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi