---
apiVersion: v1
kind: Service
metadata:
  name: redis-cart
spec:
  type: {{ .Values.service.serviceType }}
  selector:
    app: redis-cart
  ports:
  - name: redis
    port: 6379
    targetPort: 6379
{{ if eq .Values.service.serviceType "NodePort" }}
    nodePort: {{ .Values.service.nodePort }}
{{ end }}
