apiVersion: v1
kind: Pod
metadata:
  name: alpine
  labels:
    name: alpine
spec:
  serviceAccountName: vault-auth
  containers:
  - name: alpine
    image: alpine:3.9.6
    command: ["sleep", "10000"]

