apiVersion: v1
kind: Pod
metadata:
  name: web
  labels:
    app: web
spec:
  containers:
  - name: web 
    image: boygruv/kubernetes-intro-web:latest
    livenessProbe:
      tcpSocket: { port: 8000 }
    readinessProbe:
      httpGet:
        path: /index.html
        port: 8000
    securityContext:
      capabilities:
        add: ["NET_ADMIN", "SYS_PTRACE", "SYS_ADMIN"]
    volumeMounts:
    - name: app
      mountPath: /app
  initContainers:
  - name: generate-index
    image: busybox:1.31.0
    command: ['sh', '-c', 'wget -O- https://raw.githubusercontent.com/express42/otus-platform-snippets/master/Module-02/Introduction-to-Kubernetes/wget.sh | sh']
    volumeMounts:
    - name: app
      mountPath: /app
  volumes:
  - name: app
    emptyDir: {}