---
apiVersion: v1
kind: Service
metadata:
  name: front-end
  labels:
    name: front-end
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}
    {{- if (eq "NodePort" .Values.service.type) }}
    nodePort: {{ .Values.service.NodePort }}
    {{- end }}
  selector:
    name: front-end