apiVersion: v1
kind: Pod
metadata:
  name: web
  labels:
    app: web
spec:
  containers:
  - name: web 
    image: pathfinder177/kubehw1:ngalp
    ports: 
      - containerPort: 80
    volumeMounts:
    - name: app
      mountPath: web/app
  initContainers:
  - name: generate-index
    image: busybox:latest
    volumeMounts:
    - name: app
      mountPath: web/app
    command: ['sh', '-c', 'wget -O- https://raw.githubusercontent.com/express42/otus-platform-
snippets/master/Module-02/Introduction-to-Kubernetes/wget.sh | sh']
  volumes:
  - name: app
    emptyDir: {}